//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "customer")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub balance: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::lost_and_found_log::Entity")]
    LostAndFoundLog,
    #[sea_orm(has_many = "super::ride_queue::Entity")]
    RideQueue,
    #[sea_orm(has_many = "super::store_transaction::Entity")]
    StoreTransaction,
}

impl Related<super::lost_and_found_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LostAndFoundLog.def()
    }
}

impl Related<super::ride_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideQueue.def()
    }
}

impl Related<super::store_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
