//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "lost_and_found_log")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub image: String,
    pub name: String,
    pub r#type: String,
    pub color: String,
    pub last_seen_location: String,
    pub finder: String,
    pub owner: String,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::customer::Entity",
        from = "Column::Owner",
        to = "super::customer::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Customer,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::Finder",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::customer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
