//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "maintenance_log")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub task_id: String,
    pub message: String,
    pub created_at: DateTime,
    pub approved: i8,
    pub done: i8,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::maintenance_task::Entity",
        from = "Column::TaskId",
        to = "super::maintenance_task::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MaintenanceTask,
}

impl Related<super::maintenance_task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MaintenanceTask.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
