//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "menu")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub restaurant_id: String,
    pub name: String,
    pub image: String,
    pub price: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::restaurant::Entity",
        from = "Column::RestaurantId",
        to = "super::restaurant::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Restaurant,
    #[sea_orm(has_many = "super::restaurant_transaction::Entity")]
    RestaurantTransaction,
}

impl Related<super::restaurant::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Restaurant.def()
    }
}

impl Related<super::restaurant_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
