//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ride")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub image: String,
    pub price: i32,
    pub status: String,
    pub is_active: i8,
    pub assigned_staff: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ride_deletion_proposal::Entity")]
    RideDeletionProposal,
    #[sea_orm(has_many = "super::ride_queue::Entity")]
    RideQueue,
    #[sea_orm(has_many = "super::ride_staff::Entity")]
    RideStaff,
    #[sea_orm(
        belongs_to = "super::staff::Entity",
        from = "Column::AssignedStaff",
        to = "super::staff::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Staff,
}

impl Related<super::ride_deletion_proposal::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideDeletionProposal.def()
    }
}

impl Related<super::ride_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideQueue.def()
    }
}

impl Related<super::ride_staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideStaff.def()
    }
}

impl Related<super::staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Staff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
