//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "souvenir")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub store_id: String,
    pub name: String,
    pub price: i32,
    pub description: String,
    pub image: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::store::Entity",
        from = "Column::StoreId",
        to = "super::store::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Store,
    #[sea_orm(has_many = "super::store_transaction::Entity")]
    StoreTransaction,
}

impl Related<super::store::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Store.def()
    }
}

impl Related<super::store_transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StoreTransaction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
