//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "staff")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: String,
    pub password: String,
    pub role: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::lost_and_found_log::Entity")]
    LostAndFoundLog,
    #[sea_orm(has_many = "super::restaurant_staff::Entity")]
    RestaurantStaff,
    #[sea_orm(has_many = "super::ride_staff::Entity")]
    RideStaff,
}

impl Related<super::lost_and_found_log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LostAndFoundLog.def()
    }
}

impl Related<super::restaurant_staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RestaurantStaff.def()
    }
}

impl Related<super::ride_staff::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RideStaff.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
